# Generated by Django 2.0.4 on 2018-04-08 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('bug_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ('bug_id',),
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=2, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('device_id',),
            },
        ),
        migrations.CreateModel(
            name='Tester',
            fields=[
                ('tester_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('lastLogin', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='findQA.Country')),
            ],
            options={
                'ordering': ('tester_id',),
            },
        ),
        migrations.CreateModel(
            name='Tester_Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='findQA.Device')),
                ('tester_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='findQA.Tester')),
            ],
        ),
        migrations.AddField(
            model_name='bug',
            name='device_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='findQA.Device'),
        ),
        migrations.AddField(
            model_name='bug',
            name='tester_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='findQA.Tester'),
        ),
    ]
