# Generated by Django 2.0.4 on 2018-04-09 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('findQA', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tester',
            name='country',
            field=models.ForeignKey(db_column='country_code', on_delete=django.db.models.deletion.PROTECT, to='findQA.Country'),
        ),
    ]
