# Generated by Django 2.0.4 on 2018-04-09 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('findQA', '0002_auto_20180409_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='device_id',
            field=models.ForeignKey(db_column='device_id', on_delete=django.db.models.deletion.PROTECT, to='findQA.Device'),
        ),
        migrations.AlterField(
            model_name='bug',
            name='tester_id',
            field=models.ForeignKey(db_column='tester_id', on_delete=django.db.models.deletion.PROTECT, to='findQA.Tester'),
        ),
        migrations.AlterField(
            model_name='tester_device',
            name='device_id',
            field=models.ForeignKey(db_column='device_id', on_delete=django.db.models.deletion.PROTECT, to='findQA.Device'),
        ),
        migrations.AlterField(
            model_name='tester_device',
            name='tester_id',
            field=models.ForeignKey(db_column='tester_id', on_delete=django.db.models.deletion.PROTECT, to='findQA.Tester'),
        ),
    ]
