# Generated by Django 2.0.4 on 2018-04-15 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findQA', '0003_auto_20180409_0345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tester_device',
            options={'ordering': ('tester', 'device')},
        ),
        migrations.RenameField(
            model_name='bug',
            old_name='device_id',
            new_name='device',
        ),
        migrations.RenameField(
            model_name='bug',
            old_name='tester_id',
            new_name='tester',
        ),
        migrations.RenameField(
            model_name='tester',
            old_name='lastLogin',
            new_name='last_login',
        ),
        migrations.RenameField(
            model_name='tester_device',
            old_name='device_id',
            new_name='device',
        ),
        migrations.RenameField(
            model_name='tester_device',
            old_name='tester_id',
            new_name='tester',
        ),
    ]
